[package]
name = "dot"
version = "0.1.0"
edition = "2021"
description = "Dot utility"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "string"] }
clap-verbosity-flag = { version = "2.2.0" }
const_format = { version = "0.2.32", features = ["fmt"] }
env_logger = { version = "0.11.3", default-features = false, features = [
    "auto-color",
    "unstable-kv",
] }
flate2 = { version = "1.0.30" }
git2 = { version = "0.18.3", features = ["vendored-libgit2"] }
homedir = { version = "0.2.1" }
indicatif = { version = "0.17.8" }
itertools = { version = "0.13.0" }
log = { version = "0.4.21", features = ["kv"] }
tar = { version = "0.4.40" }
tempfile = { version = "3.10.1", features = ["nightly"] }
ureq = { version = "2.9.7" }
zip = { version = "1.3.0" }

[build-dependencies]
built = { version = "0.7.2" }

[profile.release]
opt-level = 3
debug = "line-tables-only"
overflow-checks = false
lto = "fat"
panic = "abort"
codegen-units = 1
