[package]
name = "dot"
version = "0.1.0"
edition = "2021"
description = "Dot utility"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "string"] }
clap-verbosity-flag = { version = "2.2.0" }
env_logger = { version = "0.11.3", default-features = false, features = [
    "auto-color",
    "unstable-kv",
] }
git2 = { version = "0.18.3", features = ["vendored-libgit2"] }
homedir = { version = "0.2.1" }
itertools = { version = "0.13.0" }
log = { version = "0.4.21", features = ["kv"] }
